# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compatible_product.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compatible_product.proto',
  package='compatible_product',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x18\x63ompatible_product.proto\x12\x12\x63ompatible_product\"N\n\x10SegmentationMask\x12\x12\n\nmask_width\x18\x01 \x01(\x03\x12\x13\n\x0bmask_height\x18\x02 \x01(\x03\x12\x11\n\tmask_data\x18\x03 \x01(\x0c\"G\n\x15NormalizedBoundingBox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\"\xca\x02\n\x07Product\x12K\n\x18normalized_bouonding_box\x18\x01 \x01(\x0b\x32).compatible_product.NormalizedBoundingBox\x12?\n\x11segmentation_mask\x18\x02 \x01(\x0b\x32$.compatible_product.SegmentationMask\x12\x17\n\x0f\x65mbedding_color\x18\x03 \x03(\x02\x12\x19\n\x11\x65mbedding_pattern\x18\x04 \x03(\x02\x12!\n\x19ground_truth_product_type\x18\x05 \x03(\t\x12\x17\n\x0fproduct_type_id\x18\x06 \x01(\x03\x12\x12\n\nproduct_id\x18\x07 \x01(\x03\x12\x1e\n\x16label_confidence_score\x18\x08 \x03(\x02\x12\r\n\x05label\x18\t \x03(\t\"\xb3\x01\n\x05Image\x12\x10\n\x08image_id\x18\x07 \x01(\x04\x12\x13\n\x0bimage_width\x18\x01 \x01(\x03\x12\x14\n\x0cimage_height\x18\x02 \x01(\x03\x12\x17\n\x0fimage_file_path\x18\x03 \x01(\t\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x12-\n\x08products\x18\x05 \x03(\x0b\x32\x1b.compatible_product.Product\x12\x11\n\toutfit_id\x18\x06 \x01(\x03\"3\n\x06Images\x12)\n\x06images\x18\x01 \x03(\x0b\x32\x19.compatible_product.Image'
)




_SEGMENTATIONMASK = _descriptor.Descriptor(
  name='SegmentationMask',
  full_name='compatible_product.SegmentationMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mask_width', full_name='compatible_product.SegmentationMask.mask_width', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask_height', full_name='compatible_product.SegmentationMask.mask_height', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask_data', full_name='compatible_product.SegmentationMask.mask_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=126,
)


_NORMALIZEDBOUNDINGBOX = _descriptor.Descriptor(
  name='NormalizedBoundingBox',
  full_name='compatible_product.NormalizedBoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='compatible_product.NormalizedBoundingBox.x1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y1', full_name='compatible_product.NormalizedBoundingBox.y1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x2', full_name='compatible_product.NormalizedBoundingBox.x2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y2', full_name='compatible_product.NormalizedBoundingBox.y2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=199,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='compatible_product.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='normalized_bouonding_box', full_name='compatible_product.Product.normalized_bouonding_box', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segmentation_mask', full_name='compatible_product.Product.segmentation_mask', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='embedding_color', full_name='compatible_product.Product.embedding_color', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='embedding_pattern', full_name='compatible_product.Product.embedding_pattern', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ground_truth_product_type', full_name='compatible_product.Product.ground_truth_product_type', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_type_id', full_name='compatible_product.Product.product_type_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='compatible_product.Product.product_id', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_confidence_score', full_name='compatible_product.Product.label_confidence_score', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='compatible_product.Product.label', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=532,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='compatible_product.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_id', full_name='compatible_product.Image.image_id', index=0,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_width', full_name='compatible_product.Image.image_width', index=1,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_height', full_name='compatible_product.Image.image_height', index=2,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_file_path', full_name='compatible_product.Image.image_file_path', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='compatible_product.Image.image_data', index=4,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='products', full_name='compatible_product.Image.products', index=5,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outfit_id', full_name='compatible_product.Image.outfit_id', index=6,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=714,
)


_IMAGES = _descriptor.Descriptor(
  name='Images',
  full_name='compatible_product.Images',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='compatible_product.Images.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=767,
)

_PRODUCT.fields_by_name['normalized_bouonding_box'].message_type = _NORMALIZEDBOUNDINGBOX
_PRODUCT.fields_by_name['segmentation_mask'].message_type = _SEGMENTATIONMASK
_IMAGE.fields_by_name['products'].message_type = _PRODUCT
_IMAGES.fields_by_name['images'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['SegmentationMask'] = _SEGMENTATIONMASK
DESCRIPTOR.message_types_by_name['NormalizedBoundingBox'] = _NORMALIZEDBOUNDINGBOX
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Images'] = _IMAGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentationMask = _reflection.GeneratedProtocolMessageType('SegmentationMask', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTATIONMASK,
  '__module__' : 'compatible_product_pb2'
  # @@protoc_insertion_point(class_scope:compatible_product.SegmentationMask)
  })
_sym_db.RegisterMessage(SegmentationMask)

NormalizedBoundingBox = _reflection.GeneratedProtocolMessageType('NormalizedBoundingBox', (_message.Message,), {
  'DESCRIPTOR' : _NORMALIZEDBOUNDINGBOX,
  '__module__' : 'compatible_product_pb2'
  # @@protoc_insertion_point(class_scope:compatible_product.NormalizedBoundingBox)
  })
_sym_db.RegisterMessage(NormalizedBoundingBox)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'compatible_product_pb2'
  # @@protoc_insertion_point(class_scope:compatible_product.Product)
  })
_sym_db.RegisterMessage(Product)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'compatible_product_pb2'
  # @@protoc_insertion_point(class_scope:compatible_product.Image)
  })
_sym_db.RegisterMessage(Image)

Images = _reflection.GeneratedProtocolMessageType('Images', (_message.Message,), {
  'DESCRIPTOR' : _IMAGES,
  '__module__' : 'compatible_product_pb2'
  # @@protoc_insertion_point(class_scope:compatible_product.Images)
  })
_sym_db.RegisterMessage(Images)


# @@protoc_insertion_point(module_scope)
